
platform :ios, '10.0'

use_frameworks!

pod "CleverTap-iOS-SDK"

target 'CTNotificationContentExample' do
  
end

target 'NotificationContent' do
  pod "CTNotificationContent", :path =>'../'
end

target 'NotificationService' do
  pod "CTNotificationService"
end
