
platform :ios, '10.0'

use_frameworks!

pod "CleverTap-iOS-SDK"

target 'CTNotificationContentExample' do
  
end

target 'NotificationContent' do
  pod "CTNotificationContent", :path =>'../'
end

target 'NotificationService' do
  pod "CTNotificationService"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
