source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!

target 'CTNotificationContentExample' do
  pod "CleverTap-iOS-SDK"
end

target 'NotificationContent' do
  pod "CTNotificationContent"
end
