platform :ios, '10.0'

use_frameworks!

pod "CleverTap-iOS-SDK"

target 'CTNotificationContentExampleSwift' do
#  pod "CleverTap-iOS-SDK"
end

target 'NotificationContent' do
  pod "CTNotificationContent", :path =>'../'
end

target 'NotificationService' do
  pod "CTNotificationService"
end
